name: mi_entorno_ds
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - scipy
  - statsmodels
  - xgboost
  - lightgbm
  - pip
  - pip:
      - kaggle
      - shap
